#ifndef NOBLE_COMPILER_PARSER_H_INCLUDED
#define NOBLE_COMPILER_PARSER_H_INCLUDED

#include <vector>
#include <memory>
#include <iostream>
#include <initializer_list>

#include "Token.h"
#include "AST/Statement.h"
#include "AST/Expression.h"

namespace Noble::Compiler
{
    /**
     * @class Parser
     * @brief Takes a list of tokens and produces an Abstract Syntax Tree (AST) for optimization and generation passes.
     *
     * Takes a list of Tokens (as generated by a Lexer object) and creates a list of statements in the form of
     * an AST. The AST is intended to be further optimized in later passes and then passes through a BytecodeVisitor
     * which generates Noble Assembly Language (NAL) sequences for execution by a VM.
     */
    class Parser
    {
    public:
        /**
         * @brief Turns a list of tokens into an AST.
         * @param tokens A list of tokens produced by a Lexer object
         * @return An AST representation of the given token list.
         */
        std::vector<AST::StatementPtr> Parse(const std::vector<Token>& tokens);
    protected:
        std::vector<Token> tokens;
        std::size_t currentToken = 0;

        [[nodiscard]] const Token* Peek(int offset = 0) const;
        [[nodiscard]] const Token* Previous() const;
        [[nodiscard]] bool AtEndOfFile() const;
        [[nodiscard]] bool Check(Token::Type type) const;

        bool Match(std::initializer_list<Token::Type> types);
        const Token* Advance();
        const Token* Consume(Token::Type type, const std::string& message);
        void Synchronise();

        AST::ExprPtr Expression();
        AST::ExprPtr Assignment();
        AST::StatementPtr Declaration();
        AST::StatementPtr VariableDeclaration();
        AST::StatementPtr Statement();
        AST::StatementPtr ExpressionStatement();
        AST::StatementPtr PrintStatement();
        AST::StatementPtr IfStatement();
        AST::ExprPtr Equality();
        AST::ExprPtr Comparison();
        AST::ExprPtr Term();
        AST::ExprPtr Factor();
        AST::ExprPtr Unary();
        AST::ExprPtr Primary();
        std::vector<AST::StatementPtr> Block();
    };
} // Noble::Compiler

#endif //NOBLE_COMPILER_PARSER_H_INCLUDED
