#ifndef BYTECODEVISITOR_H_INCLUDED
#define BYTECODEVISITOR_H_INCLUDED

#include <any>
#include <vector>
#include <unordered_map>

#include "../Frame.h"
#include "../Token.h"
#include "../AST/ExpressionVisitor.h"
#include "../AST/Statement.h"
#include "../AST/StatementVisitor.h"
#include "../Exceptions/ByteCodeVisitorException.h"

/**
 * @namespace Noble::Compiler::ByteCode
 * @brief Contains all classes related to generating NAL sequences from the AST.
 */
namespace Noble::Compiler::Bytecode
{
    /**
     * @class BytecodeVisitor
     * @brief Visits the nodes on the AST and generates NAL operations.
     *
     * Uses the visitor pattern to traverse the AST generated by the Parser and
     * writes NAL instructions to a given frame.
     */
    class BytecodeVisitor final : public AST::ExpressionVisitor, public AST::StatementVisitor
    {
    public:
        /**
         * @brief Generates NAL instructions from the given list of statements and writes them to the given frame.
         * @param statements An AST tree generated by the Parser.
         * @param frame A frame to receive the NAL instructions generated.
         */
        void GenerateOps(std::vector<AST::StatementPtr>& statements, Frame& frame);
    protected:
        /**
         * @struct LocalVariable
         * @brief Represents a local variable.
         */
        struct LocalVariable
        {
            std::string name;
            int depth = -1;
        };

        /// @brief The current frame being written to by this BytecodeVisitor object.
        Frame* frame = nullptr;

        /// @brief Map of all global variable names to their address in the bytecode stream.
        std::unordered_map<std::string, Address::Single> globalVariables;

        /// @brief The address to assign to the next declared global variable.
        Address::Single nextGlobalAddress = 0;

        /// @brief Stores all active local variables.
        std::vector<LocalVariable> localVariables;

        /// @brief
        int scopeDepth = 0;

        //ExpressionVisitor overrides
        std::any Visit(AST::BinaryExpression* binaryExpression) override;
        std::any Visit(AST::GroupingExpression* groupingExpression) override;
        std::any Visit(AST::LiteralExpression* literalExpression) override;
        std::any Visit(AST::UnaryExpression* unaryExpression) override;
        std::any Visit(AST::VariableExpression* variableExpression) override;
        std::any Visit(AST::AssignmentExpression* assignmentExpression) override;
        std::any Visit(AST::LogicalExpression* logicalExpression) override;
        std::any Visit(AST::CallExpression* callExpression) override;

        //StatementVisitor overrides
        std::any Visit(AST::ExpressionStatement* expressionStatement) override;
        std::any Visit(AST::VariableStatement* variableStatement) override;
        std::any Visit(AST::BlockStatement* blockStatement) override;
        std::any Visit(AST::IfStatement* ifStatement) override;
        std::any Visit(AST::WhileStatement* whileStatement) override;
        std::any Visit(AST::ForStatement *forStatement) override;

        //Helper methods
        /**
         * @brief Adds a named global variable to the global variables table and assigns it an address.
         * @param name The name of the global variable to define.
         */
        void DefineVariable(const std::string& name);

        /**
         * @brief Declares a local variable.
         */
        void DeclareLocalVariable(const std::string& name);

        void AddLocal(const std::string& name);

        /**
         * @brief Gets the address of a global variable from its name.
         * @param name The name of the global variable for which we want to get the address.
         * @throws ByteCodeException if the name does not match any previously declared global variable.
         * @return The address of the named global variable.
         */
        Address::Single GetGlobalVariable(const std::string& name);

        int ResolveLocal(const std::string& name) const;

        void BeginScope();

        void EndScope();

        Address::Single WriteJump(Op::Code jumpCode) const;

        void PatchJump(const Address::Single jumpAddr) const;

        void WriteLoop(const Address::Single loopStart) const;
    };
}

#endif //BYTECODEVISITOR_H_INCLUDED
